import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import process from 'node:process'

function browserPuterModelsTransform() {
  return {
    name: 'vetroai-browser-puter-models',
    enforce: 'pre',
    transform(code, id) {
      if (!id.replaceAll('\\', '/').endsWith('/src/App.jsx')) return null;
      let next = code;
      const addModelAfterCodex = (label, model) => { if (!next.includes(`"${label}": "${model}"`)) next = next.replace(/("GPT-5\.3 Codex"\s*:\s*"openai\/gpt-5\.3-codex",?)/, `$1\n  "${label}": "${model}",`); };
      addModelAfterCodex('Sonar Pro Research', 'perplexity/sonar-pro'); addModelAfterCodex('Gemini 3.1 Pro', 'gemini-3.1-pro-preview'); addModelAfterCodex('Gemini 3.7 Flash', 'gemini-3.7-flash'); addModelAfterCodex('Gemini 3.5 Flash-Lite', 'gemini-3.5-flash-lite'); addModelAfterCodex('Claude Sonnet 5', 'claude-sonnet-5'); addModelAfterCodex('Claude Haiku 4.5', 'claude-haiku-4-5'); addModelAfterCodex('Claude Opus 5', 'claude-opus-5');
      next = next.replace(/"Groq",\s*"Gemini",\s*"Mistral"/, '"Groq", "Sonar Pro Research", "Gemini 3.1 Pro", "Gemini 3.7 Flash", "Gemini 3.5 Flash-Lite", "Claude Sonnet 5", "Claude Haiku 4.5", "Claude Opus 5", "Mistral"').replace(/"Gemini 3\.5 Flash-Lite",\s*"Mistral"/, '"Gemini 3.5 Flash-Lite", "Claude Sonnet 5", "Claude Haiku 4.5", "Claude Opus 5", "Mistral"');
      const detailsAnchor = /(Groq:\s*\["Q",\s*"Fast responses"\],)/;
      if (!next.includes('"Sonar Pro Research": ["P", "Perplexity · live research"]')) next=next.replace(detailsAnchor,'$1\n    "Sonar Pro Research": ["P", "Perplexity · live research"],');
      if (!next.includes('"Gemini 3.1 Pro": ["G", "Google · strongest Gemini"]')) next=next.replace(detailsAnchor,'$1\n    "Gemini 3.1 Pro": ["G", "Google · strongest Gemini"],\n    "Gemini 3.7 Flash": ["G", "Google · fast multimodal"],\n    "Gemini 3.5 Flash-Lite": ["G", "Google · fastest lightweight"],');
      if (!next.includes('"Claude Sonnet 5": ["C", "Anthropic · balanced flagship"]')) next=next.replace(detailsAnchor,'$1\n    "Claude Sonnet 5": ["C", "Anthropic · balanced flagship"],\n    "Claude Haiku 4.5": ["C", "Anthropic · fast and efficient"],\n    "Claude Opus 5": ["C", "Anthropic · maximum capability"],');
      if (!next.includes('const PROVIDER_BRAND_ICONS =')) { const r=`\n\nconst PROVIDER_BRAND_ICONS = { [CLAUDE_FABLE_PROVIDER]: "/model-icons/claude.svg", "Claude Sonnet 5":"/model-icons/claude.svg", "Claude Haiku 4.5":"/model-icons/claude.svg", "Claude Opus 5":"/model-icons/claude.svg", "Gemini 3.1 Pro":"/model-icons/gemini.svg", "Gemini 3.7 Flash":"/model-icons/gemini.svg", "Gemini 3.5 Flash-Lite":"/model-icons/gemini.svg", Gemini:"/model-icons/gemini.svg", Mistral:"/model-icons/mistral.svg", SambaNova:"/model-icons/sambanova.svg" };\nconst ProviderBrandIcon=({provider,fallback})=>{const isOpenAI=provider==="GPT-5.6 Sol"||provider==="GPT-5.6 Terra"||provider==="GPT-5.6 Luna"||provider==="GPT-5.3 Codex";if(isOpenAI)return <img src="/model-icons/openai.svg" alt="" width="18" height="18" style={{width:18,height:18,objectFit:"contain",display:"block"}}/>;if(provider==="Auto"||provider==="Agnes")return <span style={{width:18,height:18,overflow:"hidden",display:"block"}}><img src="/logo.png" alt="VetroAI" style={{height:18,width:"auto",maxWidth:"none",display:"block"}}/></span>;const src=PROVIDER_BRAND_ICONS[provider]||(provider==="Sonar Pro Research"?"/model-icons/perplexity.svg":null);return src?<img src={src} alt="" width="18" height="18" style={{width:18,height:18,objectFit:"contain",display:"block"}}/>:<span>{fallback||"✦"}</span>};`; next=next.replace(/(const PROVIDERS = \[[^\n]+\];)/,`$1${r}`); }
      next=next.replace('<span className={`ws-model-mark model-${provider.toLowerCase().replace(/\\s+/g, "-")}`}>{mark}</span>','<span className={`ws-model-mark model-${provider.toLowerCase().replace(/\\s+/g, "-")}`} style={{background:"#09090b",color:"#fff",border:"1px solid rgba(255,255,255,.16)"}}><ProviderBrandIcon provider={provider} fallback={mark}/></span>');

      // Let the picker accept office documents too.
      next=next.replace('accept=".txt,.md,.csv,.json,.pdf,.png,.jpg,.jpeg,.gif,.webp"','accept=".txt,.md,.csv,.json,.pdf,.doc,.docx,.xls,.xlsx,.png,.jpg,.jpeg,.gif,.webp"');

      // Full Puter document extraction: text + DOCX + XLS/XLSX. PDFs continue through the app PDF extraction path.
      next=next.replace(/if \(fileCount > 0\) \{\s*throw new Error\(`\$\{effectivePuterProvider\} file uploads are not available yet\. Remove the attachment and send the text again\.`\);\s*\}/,`let puterFileContext="";\n        if(fileCount>0){\n          const docs=(Array.isArray(filesData)?filesData:filesData?[filesData]:[]).filter(f=>f instanceof File&&!f.type.startsWith("image/"));\n          for(const file of docs){\n            const lower=(file.name||"").toLowerCase(); let text="";\n            if(/\\.docx$/i.test(lower)){ if(!window.mammoth) throw new Error("Word reader failed to load."); const result=await window.mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()}); text=result.value||""; }\n            else if(/\\.(xlsx|xls)$/i.test(lower)){ if(!window.XLSX) throw new Error("Spreadsheet reader failed to load."); const wb=window.XLSX.read(await file.arrayBuffer(),{type:"array"}); text=wb.SheetNames.map(n=>\`--- SHEET: \${n} ---\\n\${window.XLSX.utils.sheet_to_csv(wb.Sheets[n])}\`).join("\\n\\n"); }\n            else if(file.type.startsWith("text/")||/\\.(txt|md|csv|json|js|jsx|ts|tsx|py|java|c|cpp|h|hpp|css|html|xml|yaml|yml|sql|log)$/i.test(lower)){ text=await file.text(); }\n            else if(/\\.pdf$/i.test(lower)){ continue; }\n            else throw new Error(\`Unsupported document: \${file.name}\`);\n            if(text.trim()) puterFileContext+=\`\\n\\n--- ATTACHED FILE: \${file.name} ---\\n\${text.trim().slice(0,60000)}\`;\n          }\n        }`);
      next=next.replace(/const puterMessages = hist\s*\.filter/,'const puterMessages = hist\n          .filter');
      next=next.replace(/if \(finalSystemPrompt\.trim\(\)\) \{\s*puterMessages\.unshift\(\{ role: "system", content: finalSystemPrompt\.trim\(\) \}\);\s*\}/,`if(puterFileContext){const lastUser=[...puterMessages].reverse().find(m=>m.role==="user");if(lastUser)lastUser.content+=\`\\n\\n[ATTACHMENTS]\${puterFileContext}\`;}\n        if(finalSystemPrompt.trim()) puterMessages.unshift({role:"system",content:finalSystemPrompt.trim()});`);

      // When a photo/image is attached and the prompt asks to modify it, use Puter's image-to-image generation instead of analysis.
      next=next.replace('if (attachedImages.length > 0) {','if (attachedImages.length > 0) {\n        const wantsImageEdit = /\\b(edit|change|modify|add|remove|replace|make me|put me|background|hair|shirt|dress|glasses|object|turn this|transform)\\b/i.test(userQuery);\n        if (wantsImageEdit && window.puter?.ai?.txt2img) {\n          setIsTyping(false); setIsWebSearching(false); setStreamStatus("streaming");\n          const source = await fileToDataUrl(attachedImages[0]);\n          let generated;\n          try { generated = await window.puter.ai.txt2img(userQuery || "Edit this image", { model: "gpt-image-2", image: source }); }\n          catch { generated = await window.puter.ai.txt2img(`${userQuery}. Preserve the person, identity, pose and important details from the uploaded reference image.`, { model: "gpt-image-2", input_image: source }); }\n          const imgUrl = generated?.src || generated?.url || (generated instanceof HTMLImageElement ? generated.src : "");\n          if(!imgUrl) throw new Error("Image edit returned no image.");\n          setMessages(prev=>{const u=[...prev];u[u.length-1]={...u[u.length-1],content:"Here is your edited image:",generatedImageUrl:imgUrl,generatedImagePrompt:userQuery,isImageGen:true,provider:"GPT Image"};return u;});\n          setIsLoading(false); setStreamStatus("idle"); setStreamingContent(""); return;\n        }');
      return {code:next,map:null};
    },
  };
}

export default defineConfig(({ mode }) => { const env=loadEnv(mode,process.cwd(),''); return { plugins:[browserPuterModelsTransform(),react()], server:{port:Number(env.VITE_PORT)||5173,strictPort:true,host:true,cors:{origin:'*',methods:'*',headers:'*'},headers:{"Cross-Origin-Opener-Policy":"same-origin-allow-popups","Access-Control-Allow-Origin":"*"},proxy:{'/api':{target:'http://127.0.0.1:3000',changeOrigin:true,secure:false}}}, optimizeDeps:{include:['leaflet','react-leaflet']} }; })
