// Intent-aware downloads for VetroAI. File export controls only appear when the user
// explicitly asks for a downloadable/file format. Generated images retain download/share.

const saveBlob=(blob,filename)=>{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)};
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=(s='')=>String(s).replace(/\r/g,'').trim();
const baseName=()=>`vetroai-${new Date().toISOString().replace(/[:.]/g,'-')}`;

const FORMAT_RULES=[
  ['pdf',/\b(pdf|portable document)\b/i],['doc',/\b(word|docx?|document file)\b/i],['xls',/\b(excel|xlsx?|spreadsheet)\b/i],
  ['csv',/\bcsv\b/i],['txt',/\b(txt|text file)\b/i],['md',/\b(markdown|\.md)\b/i],['json',/\bjson\b/i],['html',/\b(html|web page file)\b/i]
];
function requestedFormats(text=''){return FORMAT_RULES.filter(([,r])=>r.test(text)).map(([f])=>f)}
function isFileRequest(text=''){return /\b(download|export|save|give|provide|create|make|generate|send|convert)\b/i.test(text)&&requestedFormats(text).length>0}

async function exportText(text,format){const value=clean(text),name=baseName();
 if(format==='txt')return saveBlob(new Blob([value],{type:'text/plain;charset=utf-8'}),`${name}.txt`);
 if(format==='md')return saveBlob(new Blob([value],{type:'text/markdown;charset=utf-8'}),`${name}.md`);
 if(format==='json')return saveBlob(new Blob([JSON.stringify({content:value},null,2)],{type:'application/json'}),`${name}.json`);
 if(format==='html')return saveBlob(new Blob([`<!doctype html><meta charset="utf-8"><title>VetroAI</title><article style="max-width:850px;margin:40px auto;font:16px system-ui;white-space:pre-wrap">${esc(value)}</article>`],{type:'text/html;charset=utf-8'}),`${name}.html`);
 if(format==='csv'){const csv=value.split('\n').filter(Boolean).map(v=>`"${v.replace(/"/g,'""')}"`).join('\r\n');return saveBlob(new Blob([csv],{type:'text/csv;charset=utf-8'}),`${name}.csv`)}
 if(format==='doc'){const html=`<!doctype html><meta charset="utf-8"><div style="font-family:Arial;white-space:pre-wrap">${esc(value)}</div>`;return saveBlob(new Blob([html],{type:'application/msword'}),`${name}.doc`)}
 if(format==='xls'){const html=`<table><tr><td style="white-space:pre-wrap">${esc(value)}</td></tr></table>`;return saveBlob(new Blob([html],{type:'application/vnd.ms-excel'}),`${name}.xls`)}
 if(format==='pdf'){const w=window.open('','_blank');if(!w)throw new Error('Allow pop-ups to export PDF.');w.document.write(`<!doctype html><title>VetroAI export</title><style>body{font:15px Arial;max-width:850px;margin:40px auto;white-space:pre-wrap;line-height:1.5}@media print{body{margin:20mm}}</style>${esc(value)}`);w.document.close();setTimeout(()=>{w.focus();w.print()},250)}
}
async function imageBlob(url,type='image/png'){const res=await fetch(url),src=await res.blob();if(type==='image/png'&&src.type==='image/png')return src;const bitmap=await createImageBitmap(src),canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d').drawImage(bitmap,0,0);return await new Promise(resolve=>canvas.toBlob(resolve,type,type==='image/jpeg'?.94:undefined))}
async function saveImage(url,ext){saveBlob(await imageBlob(url,ext==='jpg'?'image/jpeg':'image/png'),`${baseName()}.${ext}`)}
async function shareImage(url){const blob=await imageBlob(url),file=new File([blob],`${baseName()}.png`,{type:'image/png'});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]})))return navigator.share({files:[file],title:'VetroAI image'});saveBlob(blob,file.name)}
function label(f){return({pdf:'PDF',doc:'Word (.doc)',xls:'Spreadsheet (.xls)',csv:'CSV',txt:'Text (.txt)',md:'Markdown (.md)',json:'JSON',html:'HTML'})[f]}
function menu(items,x,y){document.querySelector('.vetro-download-menu')?.remove();const el=document.createElement('div');el.className='vetro-download-menu';Object.assign(el.style,{position:'fixed',zIndex:999999,left:`${Math.min(x,innerWidth-220)}px`,top:`${Math.min(y,innerHeight-340)}px`,width:'205px',padding:'7px',borderRadius:'12px',background:'#111113',border:'1px solid #303034'});items.forEach(([name,fn])=>{const b=document.createElement('button');b.textContent=name;b.style.cssText='display:block;width:100%;padding:9px 10px;border:0;border-radius:8px;background:transparent;color:#eee;text-align:left;cursor:pointer';b.onclick=async()=>{el.remove();try{await fn()}catch(e){alert(e.message||'Download failed')}};el.appendChild(b)});document.body.appendChild(el);setTimeout(()=>document.addEventListener('click',()=>el.remove(),{once:true}),0)}
function previousUserText(row){let n=row.previousElementSibling;while(n){const t=n.innerText?.trim()||'';if(t&&!n.querySelector('.response-model-icon'))return t;n=n.previousElementSibling}return ''}
function enhance(){document.querySelectorAll('.msg-row').forEach(row=>{if(row.dataset.downloadEnhanced)return;const text=row.innerText?.trim();if(!text)return;const request=previousUserText(row),formats=requestedFormats(request);if(isFileRequest(request)&&formats.length){const host=row.querySelector('.msg-actions')||row,b=document.createElement('button');b.type='button';b.textContent='↓';b.title=`Download ${formats.map(label).join(' / ')}`;b.className='vetro-export-btn';b.style.cssText='margin-left:6px;width:30px;height:30px;border-radius:8px;border:1px solid #303034;background:#111113;color:#ddd;cursor:pointer';b.onclick=e=>{e.stopPropagation();const items=formats.map(f=>[label(f),()=>exportText(text,f)]);if(items.length===1)items[0][1]();else menu(items,e.clientX,e.clientY)};host.appendChild(b)}row.dataset.downloadEnhanced='1'});
 document.querySelectorAll('img').forEach(img=>{if(img.dataset.vetroImageActions||!img.src||img.width<180||img.height<120)return;const row=img.closest('.msg-row');if(!row)return;const wrap=document.createElement('span');wrap.style.cssText='display:inline-flex;gap:6px;margin:7px 0 0 7px;vertical-align:top';const make=(label,title,fn)=>{const b=document.createElement('button');b.textContent=label;b.title=title;b.style.cssText='border:1px solid #303034;background:#111113;color:#eee;border-radius:8px;padding:7px 9px;cursor:pointer';b.onclick=e=>{e.stopPropagation();fn().catch(err=>alert(err.message||'Action failed'))};return b};wrap.append(make('PNG','Download PNG',()=>saveImage(img.src,'png')),make('JPG','Download JPG',()=>saveImage(img.src,'jpg')),make('Share','Share image',()=>shareImage(img.src)));img.insertAdjacentElement('afterend',wrap);img.dataset.vetroImageActions='1'})}
if(typeof window!=='undefined'){new MutationObserver(enhance).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('load',enhance);setInterval(enhance,1800)}
